version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: car_safety_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: car_safety_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

volumes:
  mongo_data:
